# Example unifi-rpc configuration file
# Place this file at ~/.unifi-rpc.yaml or specify with --config flag

# Server configuration
port: 5000
address: "0.0.0.0"

# UniFi Switch SSH connection
switch_host: "10.0.24.136" # IP address or hostname of your UniFi switch
ssh_port: 22 # SSH port (default: 22)
ssh_username: "root" # SSH username (default: root)
ssh_key_path: "~/.ssh/id_rsa" # Path to SSH private key file

# Example usage:
# Power control requires only the X-Port header:
#   curl -X POST -H "X-Port: 3" -H "Content-Type: application/json" \
#     -d '{"jsonrpc":"2.0","method":"power.get","id":1}' \
#     http://localhost:5000/
#
# Available RPC methods:
#   - power.get: Get current power state
#   - power.set: Set power state (params: {"state": "on|off|soft|cycle|reset"})
#   - boot.device: Set boot device (acknowledged but not implemented)
#   - ping: Health check (returns "pong")
